# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

[git_branch]
style = "bold red"
disabled = false

[git_status]
disabled = false

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"
format = "[$symbol $percentage]($style) "

[[battery.display]]
threshold = 30
style = "bold red"

[directory]
truncation_length = 3
truncation_symbol = ".../"

[sudo]
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = false
